#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniCadeAndroid.Resource", IsApplication=true)]

namespace UniCadeAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050026
			public const int ApiSelectionSpinner = 2131034150;
			
			// aapt resource value: 0x7f050044
			public const int ApplyButton = 2131034180;
			
			// aapt resource value: 0x7f050037
			public const int BackupDatabaseButton = 2131034167;
			
			// aapt resource value: 0x7f050031
			public const int BoxBackImageCheckbox = 2131034161;
			
			// aapt resource value: 0x7f05000e
			public const int BoxBackImageView = 2131034126;
			
			// aapt resource value: 0x7f050030
			public const int BoxFrontImageCheckbox = 2131034160;
			
			// aapt resource value: 0x7f05000d
			public const int BoxFrontImageView = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int CloseButton = 2131034133;
			
			// aapt resource value: 0x7f050021
			public const int ConsoleImageView = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int ConsoleSelectionSpinner = 2131034149;
			
			// aapt resource value: 0x7f050002
			public const int ConsoleTextView = 2131034114;
			
			// aapt resource value: 0x7f050028
			public const int CriticScoreCheckbox = 2131034152;
			
			// aapt resource value: 0x7f050004
			public const int CriticScoreTextView = 2131034116;
			
			// aapt resource value: 0x7f05003d
			public const int DeleteAllLocalImagesButton = 2131034173;
			
			// aapt resource value: 0x7f05002d
			public const int DescriptionCheckbox = 2131034157;
			
			// aapt resource value: 0x7f05000a
			public const int DescriptonTextView = 2131034122;
			
			// aapt resource value: 0x7f05003a
			public const int DisplayConsoleLogoCheckbox = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int DisplayEsrbLogoCheckbox = 2131034171;
			
			// aapt resource value: 0x7f050041
			public const int EnterLicenseKeyButton = 2131034177;
			
			// aapt resource value: 0x7f050007
			public const int EsrbDescriptorsTextView = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int EsrbLogoImageView = 2131034128;
			
			// aapt resource value: 0x7f05002b
			public const int EsrbRatingCheckbox = 2131034155;
			
			// aapt resource value: 0x7f050006
			public const int EsrbRatingTextView = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int FavoriteCheckbox = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int GameInfoViewRelativeLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int GameInfoViewRelativeLayout2 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int GameInfoViewRelativeLayout3 = 2131034132;
			
			// aapt resource value: 0x7f05001e
			public const int GameSelectionListView = 2131034142;
			
			// aapt resource value: 0x7f05002e
			public const int GenresCheckbox = 2131034158;
			
			// aapt resource value: 0x7f050023
			public const int GlobalfavoritesCheckbox = 2131034147;
			
			// aapt resource value: 0x7f05001f
			public const int InfoButton = 2131034143;
			
			// aapt resource value: 0x7f050008
			public const int LaunchCountTextView = 2131034120;
			
			// aapt resource value: 0x7f050035
			public const int LoadBackupButton = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int LoadDatabaseButton = 2131034164;
			
			// aapt resource value: 0x7f050038
			public const int LoadDatabaseOnStartupCheckbox = 2131034168;
			
			// aapt resource value: 0x7f05001c
			public const int LoginButton = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int LoginTextView = 2131034136;
			
			// aapt resource value: 0x7f05002f
			public const int OtherAvailablePlatformsCheckbox = 2131034159;
			
			// aapt resource value: 0x7f05001a
			public const int PasswordEditText = 2131034138;
			
			// aapt resource value: 0x7f05002c
			public const int PlayerCountCheckbox = 2131034156;
			
			// aapt resource value: 0x7f050005
			public const int PlayersTextView = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int PublisherTextView = 2131034115;
			
			// aapt resource value: 0x7f05002a
			public const int PubusherDeveloperCheckbox = 2131034154;
			
			// aapt resource value: 0x7f050017
			public const int RefreshButton = 2131034135;
			
			// aapt resource value: 0x7f050027
			public const int ReleaseDateCheckbox = 2131034151;
			
			// aapt resource value: 0x7f050009
			public const int ReleaseDateTextView = 2131034121;
			
			// aapt resource value: 0x7f050039
			public const int RescanLocalLibrariesOnStartupCheckbox = 2131034169;
			
			// aapt resource value: 0x7f050013
			public const int RescrapeConsoleButton = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int RescrapeGameButton = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int SaveButton = 2131034134;
			
			// aapt resource value: 0x7f050036
			public const int SaveDatabaseButton = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int ScreenshotImageCheckbox = 2131034162;
			
			// aapt resource value: 0x7f05000f
			public const int ScreenshotImageView = 2131034127;
			
			// aapt resource value: 0x7f050024
			public const int SearchBarEditTExt = 2131034148;
			
			// aapt resource value: 0x7f050020
			public const int SettingsButton = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int SettingsViewLinearLayout = 2131034112;
			
			// aapt resource value: 0x7f050033
			public const int SettingsViewRelativeLayout0 = 2131034163;
			
			// aapt resource value: 0x7f05001b
			public const int SettingsViewRelativeLayout1 = 2131034139;
			
			// aapt resource value: 0x7f05003c
			public const int SettingsViewRelativeLayout2 = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int SettingsViewRelativeLayout3 = 2131034175;
			
			// aapt resource value: 0x7f050042
			public const int SettingsViewRelativeLayout4 = 2131034178;
			
			// aapt resource value: 0x7f050022
			public const int ShowFavoritesCheckbox = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int TitleTextView = 2131034113;
			
			// aapt resource value: 0x7f05003e
			public const int UniCadeCloudButton = 2131034174;
			
			// aapt resource value: 0x7f050029
			public const int UserScoreCheckbox = 2131034153;
			
			// aapt resource value: 0x7f050019
			public const int UsernameEditText = 2131034137;
			
			// aapt resource value: 0x7f050040
			public const int WebScraperSettingsButton = 2131034176;
			
			// aapt resource value: 0x7f05001d
			public const int relativeLayout = 2131034141;
			
			// aapt resource value: 0x7f050043
			public const int relativeLayout5 = 2131034179;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameInfoWindow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ScraperSettingsView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SettingsView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
