#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("UniCadeAndroid.Resource", IsApplication=true)]

namespace UniCadeAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int accent = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int cellback = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int divider = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int error = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int hint_color = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int icons = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int primary = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int primary_dark = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int primary_light = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int primary_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int secondary_text = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int success_color = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int warning_color = 2130968589;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_padding = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textview_drawablePadding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_error = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_fingerprint_error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_fingerprint_success = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_fp_40px = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_secure = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int UniCadeIcon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07003b
			public const int ApiSelectionSpinner = 2131165243;
			
			// aapt resource value: 0x7f070049
			public const int ApplyButton = 2131165257;
			
			// aapt resource value: 0x7f07004f
			public const int BackupDatabaseButton = 2131165263;
			
			// aapt resource value: 0x7f070046
			public const int BoxBackImageCheckbox = 2131165254;
			
			// aapt resource value: 0x7f070017
			public const int BoxBackImageView = 2131165207;
			
			// aapt resource value: 0x7f070045
			public const int BoxFrontImageCheckbox = 2131165253;
			
			// aapt resource value: 0x7f070016
			public const int BoxFrontImageView = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int CloseButton = 2131165212;
			
			// aapt resource value: 0x7f07002a
			public const int ConsoleImageView = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int ConsoleSelectionSpinner = 2131165229;
			
			// aapt resource value: 0x7f07000b
			public const int ConsoleTextView = 2131165195;
			
			// aapt resource value: 0x7f07003d
			public const int CriticScoreCheckbox = 2131165245;
			
			// aapt resource value: 0x7f07000d
			public const int CriticScoreTextView = 2131165197;
			
			// aapt resource value: 0x7f070055
			public const int DeleteAllLocalImagesButton = 2131165269;
			
			// aapt resource value: 0x7f070042
			public const int DescriptionCheckbox = 2131165250;
			
			// aapt resource value: 0x7f070013
			public const int DescriptonTextView = 2131165203;
			
			// aapt resource value: 0x7f070053
			public const int DisplayModernESRBIconsCheckbox = 2131165267;
			
			// aapt resource value: 0x7f07001e
			public const int DownloadInfoButton = 2131165214;
			
			// aapt resource value: 0x7f070052
			public const int EnableFingerprintSecurityCheckbox = 2131165266;
			
			// aapt resource value: 0x7f070059
			public const int EnterLicenseKeyButton = 2131165273;
			
			// aapt resource value: 0x7f070010
			public const int EsrbDescriptorsTextView = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int EsrbLogoImageView = 2131165209;
			
			// aapt resource value: 0x7f070040
			public const int EsrbRatingCheckbox = 2131165248;
			
			// aapt resource value: 0x7f07000f
			public const int EsrbRatingTextView = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int FavoriteCheckbox = 2131165204;
			
			// aapt resource value: 0x7f07002c
			public const int GameCountTextView = 2131165228;
			
			// aapt resource value: 0x7f070009
			public const int GameInfoViewLinearLayout = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int GameInfoViewRelativeLayout1 = 2131165205;
			
			// aapt resource value: 0x7f07001a
			public const int GameInfoViewRelativeLayout2 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int GameInfoViewRelativeLayout3 = 2131165211;
			
			// aapt resource value: 0x7f070028
			public const int GameSelectionListView = 2131165224;
			
			// aapt resource value: 0x7f070043
			public const int GenresCheckbox = 2131165251;
			
			// aapt resource value: 0x7f070003
			public const int Image = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int LaunchCountTextView = 2131165201;
			
			// aapt resource value: 0x7f07004c
			public const int LoadBackupButton = 2131165260;
			
			// aapt resource value: 0x7f07004b
			public const int LoadDatabaseButton = 2131165259;
			
			// aapt resource value: 0x7f070026
			public const int LoginButton = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int LoginTextView = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int LoginViewLinearLayout = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int LoginViewRelativeLayout1 = 2131165221;
			
			// aapt resource value: 0x7f070044
			public const int OtherAvailablePlatformsCheckbox = 2131165252;
			
			// aapt resource value: 0x7f070024
			public const int PasswordEditText = 2131165220;
			
			// aapt resource value: 0x7f070051
			public const int PasswordProtectSettingsCheckbox = 2131165265;
			
			// aapt resource value: 0x7f070041
			public const int PlayerCountCheckbox = 2131165249;
			
			// aapt resource value: 0x7f07000e
			public const int PlayersTextView = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int PublisherTextView = 2131165196;
			
			// aapt resource value: 0x7f07003f
			public const int PubusherDeveloperCheckbox = 2131165247;
			
			// aapt resource value: 0x7f07003c
			public const int ReleaseDateCheckbox = 2131165244;
			
			// aapt resource value: 0x7f070012
			public const int ReleaseDateTextView = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int SaveButton = 2131165213;
			
			// aapt resource value: 0x7f07004e
			public const int SaveDatabaseButton = 2131165262;
			
			// aapt resource value: 0x7f070047
			public const int ScreenshotImageCheckbox = 2131165255;
			
			// aapt resource value: 0x7f070018
			public const int ScreenshotImageView = 2131165208;
			
			// aapt resource value: 0x7f07002b
			public const int SearchBarEditTExt = 2131165227;
			
			// aapt resource value: 0x7f070029
			public const int SettingsButton = 2131165225;
			
			// aapt resource value: 0x7f07003a
			public const int SettingsViewLinearLayout = 2131165242;
			
			// aapt resource value: 0x7f07004a
			public const int SettingsViewRelativeLayout0 = 2131165258;
			
			// aapt resource value: 0x7f07004d
			public const int SettingsViewRelativeLayout1 = 2131165261;
			
			// aapt resource value: 0x7f070054
			public const int SettingsViewRelativeLayout2 = 2131165268;
			
			// aapt resource value: 0x7f070057
			public const int SettingsViewRelativeLayout3 = 2131165271;
			
			// aapt resource value: 0x7f070050
			public const int ShowSplashScreenCheckbox = 2131165264;
			
			// aapt resource value: 0x7f070000
			public const int Text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Text1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Text2 = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int TitleTextView = 2131165194;
			
			// aapt resource value: 0x7f070056
			public const int UniCadeCloudButton = 2131165270;
			
			// aapt resource value: 0x7f07003e
			public const int UserScoreCheckbox = 2131165246;
			
			// aapt resource value: 0x7f070023
			public const int UsernameEditText = 2131165219;
			
			// aapt resource value: 0x7f070058
			public const int WebScraperSettingsButton = 2131165272;
			
			// aapt resource value: 0x7f07002e
			public const int authenticated_panel = 2131165230;
			
			// aapt resource value: 0x7f070008
			public const int cancel_button = 2131165192;
			
			// aapt resource value: 0x7f070020
			public const int edittext = 2131165216;
			
			// aapt resource value: 0x7f070031
			public const int error_panel = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int error_text1 = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int error_text2 = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int failed_scan_again_button = 2131165236;
			
			// aapt resource value: 0x7f070004
			public const int fingerprint_container = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int fingerprint_description = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int fingerprint_icon = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int fingerprint_status = 2131165191;
			
			// aapt resource value: 0x7f070037
			public const int initial_panel = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int initial_panel_textview = 2131165240;
			
			// aapt resource value: 0x7f070027
			public const int relativeLayout = 2131165223;
			
			// aapt resource value: 0x7f070048
			public const int relativeLayout5 = 2131165256;
			
			// aapt resource value: 0x7f070030
			public const int scan_again_button = 2131165232;
			
			// aapt resource value: 0x7f070035
			public const int scan_in_progress = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int scan_in_progress_textview = 2131165238;
			
			// aapt resource value: 0x7f070039
			public const int start_authentication_scan_buton = 2131165241;
			
			// aapt resource value: 0x7f07001f
			public const int textView = 2131165215;
			
			// aapt resource value: 0x7f07002f
			public const int validated_textview = 2131165231;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fingerprintmanager_api = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomGameListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomSpinnerItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_scanning_for_fingerprint = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GameInfoView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InputDialogView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoginView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int panel_authenticated = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int panel_error = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int panel_fingerprint_scan_in_progress = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int panel_initial = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ScraperSettingsView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SettingsView = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int action_settings = 2131099672;
			
			// aapt resource value: 0x7f060005
			public const int activity_fingeprintauthenticatoractivity_description = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int activity_fingeprintauthenticatoractivity_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int activity_fingerprintmanagerapiactivity_description = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int activity_fingerprintmanagerapiactivity_title = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int authenticated_user_message = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int authentication_failed_message = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int cancel = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int fingerprint_description = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int fingerprint_hint = 2131099658;
			
			// aapt resource value: 0x7f06001e
			public const int fingerprint_not_recognized = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int fingerprint_success = 2131099679;
			
			// aapt resource value: 0x7f06000b
			public const int keyguard_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int missing_fingerprint_permissions = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int missing_fingerprint_scanner = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int new_fingerprint_enrolled_description = 2131099680;
			
			// aapt resource value: 0x7f06000e
			public const int ok = 2131099662;
			
			// aapt resource value: 0x7f06001b
			public const int password = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int password_description = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int purchase = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int register_fingerprint = 2131099663;
			
			// aapt resource value: 0x7f060017
			public const int scan_cancelled_by_user = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int scan_fingerprint_in_progress = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int scan_fingerprint_not_available = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int scan_fingerprint_ready = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int scan_fingerprint_start = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int scan_fingerprint_stop = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int scan_fingerprint_try_again = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int secure_lock_not_setup = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int sign_in = 2131099674;
			
			// aapt resource value: 0x7f060021
			public const int use_fingerprint_in_future = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int use_fingerprint_to_authenticate_key = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int use_fingerprint_to_authenticate_title = 2131099682;
			
			// aapt resource value: 0x7f060019
			public const int use_password = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
