#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniCadeAndroid.Resource", IsApplication=true)]

namespace UniCadeAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int cellback = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int UniCadeIcon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int ApiSelectionSpinner = 2131099691;
			
			// aapt resource value: 0x7f060039
			public const int ApplyButton = 2131099705;
			
			// aapt resource value: 0x7f06003f
			public const int BackupDatabaseButton = 2131099711;
			
			// aapt resource value: 0x7f060036
			public const int BoxBackImageCheckbox = 2131099702;
			
			// aapt resource value: 0x7f060012
			public const int BoxBackImageView = 2131099666;
			
			// aapt resource value: 0x7f060035
			public const int BoxFrontImageCheckbox = 2131099701;
			
			// aapt resource value: 0x7f060011
			public const int BoxFrontImageView = 2131099665;
			
			// aapt resource value: 0x7f060019
			public const int CloseButton = 2131099673;
			
			// aapt resource value: 0x7f060025
			public const int ConsoleImageView = 2131099685;
			
			// aapt resource value: 0x7f060029
			public const int ConsoleSelectionSpinner = 2131099689;
			
			// aapt resource value: 0x7f060006
			public const int ConsoleTextView = 2131099654;
			
			// aapt resource value: 0x7f06002d
			public const int CriticScoreCheckbox = 2131099693;
			
			// aapt resource value: 0x7f060008
			public const int CriticScoreTextView = 2131099656;
			
			// aapt resource value: 0x7f060045
			public const int DeleteAllLocalImagesButton = 2131099717;
			
			// aapt resource value: 0x7f060032
			public const int DescriptionCheckbox = 2131099698;
			
			// aapt resource value: 0x7f06000e
			public const int DescriptonTextView = 2131099662;
			
			// aapt resource value: 0x7f060042
			public const int DisplayConsoleLogoCheckbox = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int DisplayEsrbLogoCheckbox = 2131099715;
			
			// aapt resource value: 0x7f060049
			public const int EnterLicenseKeyButton = 2131099721;
			
			// aapt resource value: 0x7f06000b
			public const int EsrbDescriptorsTextView = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int EsrbLogoImageView = 2131099668;
			
			// aapt resource value: 0x7f060030
			public const int EsrbRatingCheckbox = 2131099696;
			
			// aapt resource value: 0x7f06000a
			public const int EsrbRatingTextView = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int FavoriteCheckbox = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int GameInfoViewLinearLayout = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int GameInfoViewRelativeLayout1 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int GameInfoViewRelativeLayout2 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int GameInfoViewRelativeLayout3 = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int GameSelectionListView = 2131099683;
			
			// aapt resource value: 0x7f060033
			public const int GenresCheckbox = 2131099699;
			
			// aapt resource value: 0x7f060027
			public const int GlobalfavoritesCheckbox = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int LaunchCountTextView = 2131099660;
			
			// aapt resource value: 0x7f06003c
			public const int LoadBackupButton = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int LoadDatabaseButton = 2131099707;
			
			// aapt resource value: 0x7f060040
			public const int LoadDatabaseOnStartupCheckbox = 2131099712;
			
			// aapt resource value: 0x7f060021
			public const int LoginButton = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int LoginTextView = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int LoginViewLinearLayout = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int LoginViewRelativeLayout1 = 2131099680;
			
			// aapt resource value: 0x7f060034
			public const int OtherAvailablePlatformsCheckbox = 2131099700;
			
			// aapt resource value: 0x7f06001f
			public const int PasswordEditText = 2131099679;
			
			// aapt resource value: 0x7f060031
			public const int PlayerCountCheckbox = 2131099697;
			
			// aapt resource value: 0x7f060009
			public const int PlayersTextView = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int PublisherTextView = 2131099655;
			
			// aapt resource value: 0x7f06002f
			public const int PubusherDeveloperCheckbox = 2131099695;
			
			// aapt resource value: 0x7f06001b
			public const int RefreshButton = 2131099675;
			
			// aapt resource value: 0x7f06002c
			public const int ReleaseDateCheckbox = 2131099692;
			
			// aapt resource value: 0x7f06000d
			public const int ReleaseDateTextView = 2131099661;
			
			// aapt resource value: 0x7f060041
			public const int RescanLocalLibrariesOnStartupCheckbox = 2131099713;
			
			// aapt resource value: 0x7f060017
			public const int RescrapeConsoleButton = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int RescrapeGameButton = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int SaveButton = 2131099674;
			
			// aapt resource value: 0x7f06003e
			public const int SaveDatabaseButton = 2131099710;
			
			// aapt resource value: 0x7f060037
			public const int ScreenshotImageCheckbox = 2131099703;
			
			// aapt resource value: 0x7f060013
			public const int ScreenshotImageView = 2131099667;
			
			// aapt resource value: 0x7f060028
			public const int SearchBarEditTExt = 2131099688;
			
			// aapt resource value: 0x7f060024
			public const int SettingsButton = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int SettingsViewLinearLayout = 2131099690;
			
			// aapt resource value: 0x7f06003a
			public const int SettingsViewRelativeLayout0 = 2131099706;
			
			// aapt resource value: 0x7f06003d
			public const int SettingsViewRelativeLayout1 = 2131099709;
			
			// aapt resource value: 0x7f060044
			public const int SettingsViewRelativeLayout2 = 2131099716;
			
			// aapt resource value: 0x7f060047
			public const int SettingsViewRelativeLayout3 = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int SettingsViewRelativeLayout4 = 2131099722;
			
			// aapt resource value: 0x7f060026
			public const int ShowFavoritesCheckbox = 2131099686;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int TitleTextView = 2131099653;
			
			// aapt resource value: 0x7f060046
			public const int UniCadeCloudButton = 2131099718;
			
			// aapt resource value: 0x7f06002e
			public const int UserScoreCheckbox = 2131099694;
			
			// aapt resource value: 0x7f06001e
			public const int UsernameEditText = 2131099678;
			
			// aapt resource value: 0x7f060048
			public const int WebScraperSettingsButton = 2131099720;
			
			// aapt resource value: 0x7f060022
			public const int relativeLayout = 2131099682;
			
			// aapt resource value: 0x7f060038
			public const int relativeLayout5 = 2131099704;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomGameListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomSpinnerItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GameInfoView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScraperSettingsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SettingsView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
